export const GET_PRODUCT_LOAD = "GET_PRODUCT_LOAD";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";

export const POST_PRODUCT_SUCCESS = "POST_PRODUCT_SUCCESS"
export const POST_PRODUCT_FAIL = "POST_PRODUCT_FAIL"

export const GET_ONEPRODUCT_SUCCESS = "GET_ONEPRODUCT_SUCCESS"
export const GET_ONEPRODUCT_FAIL = "GET_ONEPRODUCT_FAIL"

export const UPDATE_PRODUCT = "UPDATE_PRODUCT"

export const DELETE_PRODUCT = "DELETE_PRODUCT"

export const SEARCH_PRODUCT = "SEARCH_PRODUCT"


export const GET_CLIENTS_LOAD = "GET_CLIENTS_LOAD"
export const GET_CLIENTS_SUCCESS = "GET_CLIENTS_SUCCESS"
export const GET_CLIENTS_FAIL = "GET_CLIENTS_FAIL"

export const POST_CLIENT_SUCCESS = "POST_CLIENT_SUCCESS "
export const POST_CLIENT_FAIL = "POST_CLIENT_FAIL "

export const GET_ONECLIENT = "GET_ONECLIENT"

export const UPDATE_CLIENT = "UPDATE_CLIENT"

export const DELETE_CLIENT = "DELETE_CLIENT"

export const SEARCH_CLIENT = "SEARCH_CLIENT"

export const ADD_PRODUCTS_ORDER = "ADD_PRODUCTS_ORDER"
export const ADD_CLIENT_ORDER = "ADD_CLIENT_ORDER"